# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: activity_management_development

test:
  <<: *default
  database: activity_management_test

#first
# database: naomtes
#   username: naomtes
#   password: kpyFk3z2zk7Jsja
#   host: naomtes.c55k4n1tbtoz.us-east-2.rds.amazonaws.com
#   port: 5432

#last
# database: activitymanagement
#   username: postgres
#   password: If54EdSwMFd1reORA8of
#   host: activitymanagement.c55k4n1tbtoz.us-east-2.rds.amazonaws.com
#   port: 5432

production:
  <<: *default
  database: activitymanagement
  username: postgres
  password: If54EdSwMFd1reORA8of
  host: activitymanagement.czbtg97xdzte.us-east-2.rds.amazonaws.com
  port: 5432
